## <strong>2. NumPy: Universal Functions (UFunc)</strong>

In [12]:
import numpy as np

In [13]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# [+] 함수 테스트
value = np.random.randint(1, 10, size = 5)

#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [14]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1, 100)
big_array = np.random.randint(1,100, size = 1000000)

In [15]:
big_array[:100]

array([73,  4, 22, 68, 81, 85, 39,  7, 79, 20, 42, 53, 79, 76, 34, 70, 84,
       89, 95, 20,  5,  2, 25, 72,  3, 19, 76, 89, 12, 15, 12, 57, 51, 62,
       53, 13, 19, 38, 66, 12, 91, 64, 47, 39, 56, 95, 82, 85, 78, 23, 67,
       51, 64, 73, 53, 93, 77, 81, 11, 50, 66, 74, 91, 51,  7,  4, 41,  3,
       86, 38, 46, 60, 47, 75, 82, 24,  5, 78, 98, 29, 84, 86, 16, 29, 33,
       64, 50, 79,  4, 93, 54, 11, 75, 97, 67, 61,  6, 52, 20, 18],
      dtype=int32)

In [16]:
%timeit

# [+] Python loop를 통한 역수 계산 
compute_reciprocals(big_array)

array([0.01369863, 0.25      , 0.04545455, ..., 0.01086957, 0.0125    ,
       0.01724138], shape=(1000000,))

In [17]:
%timeit

# [+] NumPy ufunc을 통한 벡터화된 역수 계산
1 / big_array

array([0.01369863, 0.25      , 0.04545455, ..., 0.01086957, 0.0125    ,
       0.01724138], shape=(1000000,))

#### <strong>유니버설 함수들</strong>

In [18]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [19]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [20]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [ ]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

In [21]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [22]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [23]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0,100,5)
x

array([  0.,  25.,  50.,  75., 100.])

In [26]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0,100,11)
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [29]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [30]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
aggr

np.int64(10)

In [31]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.reduce(x)
aggr

np.int64(24)

In [33]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)
accum

array([ 1,  3,  6, 10])

In [34]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
accum

array([ 1,  2,  6, 24])

In [42]:
# 집계 함수: sum()
np.random.seed(3) #랜덤시드 for 재현성을 위해서
arr = np.random.rand(1000000) # [+] 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015323


In [43]:
# sum(): Python 내장함수
%timeit sum(arr)

261 ms ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [44]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

2.04 ms ± 114 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
#numpy함수가 파이썬보다 빠르다.

In [53]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr,25))
print("variance =", np.var(arr))
print("standard deviation =", np.std(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr > 1))
print("Is every number greater than 0? =", np.all(arr > 0)) 

max = 9
min = 0
mean = 4.5
median = 4.5
percentile = 3.0
variance = 5.75
standard deviation = 2.3979157616563596
index of maximum value = 5
index of minimum value = 1
Is there any number greater than 1? = True
Is every number greater than 0? = False


In [51]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [54]:
# [+] 행 방향으로 집계 (row sum)
np.sum(arr, axis=0)

array([14, 13, 13, 14])

In [55]:
# [+] 열 방향으로 집계 (column sum)
np.sum(arr, axis=1)

array([11, 24, 19])